id: P000713
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD985
  title: 'རྫོགས་ཆེན་དགོན་པའི་བསང་གསོལ་སྐོར། '
  author: ''
  volumes:
    2a365fa08a664d7699d947a8b9ae622f:
      image_group_id: I2PD20142
      title: ''
      volume_number: 1
      total_pages: 798
    0e607d2a435f418bb8451a95c681a50b:
      image_group_id: I2PD20143
      title: ''
      volume_number: 2
      total_pages: 1428
