id: P000713
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-16 16:38:28.480779
source_metadata:
  id: bdr:W3PD985
  title: 'རྫོགས་ཆེན་དགོན་པའི་བསང་གསོལ་སྐོར། '
  author: ''
  volumes:
    2a365fa08a664d7699d947a8b9ae622f:
      image_group_id: I2PD20142
      title: ''
      volume_number: 1
      total_pages: 798
      base_file: v001.txt
    0e607d2a435f418bb8451a95c681a50b:
      image_group_id: I2PD20143
      title: ''
      volume_number: 2
      total_pages: 1428
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
